### ISSUE TITLE
代码字体无法修改，始终为有衬线不等宽字体

### ISSUE THREAD

**Issue by Fang-Lansheng** [mtobeiyf/whu-thesis#10]
启用 minted 后，代码块中的字体不是等宽的（似乎是原文默认字体？设置 fontfamily 为其他字体时仍然有衬线不等宽）
![GwMdY9.png](https://s1.ax1x.com/2020/04/04/GwMdY9.png)
![Gw8lrt.png](https://s1.ax1x.com/2020/04/04/Gw8lrt.png)
Listings 中的字体格式也比较奇怪，虽然是等宽的但是字母间距好像有点大
![Gw39nP.png](https://s1.ax1x.com/2020/04/04/Gw39nP.png)
我以为是 `WHUBachelor.cls` 中字体设置的问题，但是注释了如下两行后仍然没有变化
```
\setsansfont{Times New Roman}
\setmonofont{Times New Roman}
```
新接触 LaTeX 不太明白其中原理，感觉这样看起来还是不太美观，请问该如何解决这个问题呢？

**Comment by tanukihee** [comment]
初步认为是 `txfontsb` 包的原因，字母间距过大是强行等宽的原因，可自行指定等宽字体

**Comment by Fang-Lansheng** [comment]
感谢回复！测试发现启用另一款数学字体（同时注释掉之前提到的两行可以解决问题）
```
% \RequirePackage{txfontsb} % Times 风格（数学）字体
% 或
\RequirePackage{unicode-math}
\setmathfont{TeX Gyre Termes Math} % 另一款 Times 风格数学字体，需要单独安装
% 以上两者任选其一

%%% ---- 定义字体 ----- %%%
\renewcommand{\normalsize}{\zihao{-4}} % 正常字号
\setmainfont{Times New Roman}
% \setsansfont{Times New Roman}
% \setmonofont{Times New Roman}
```
效果如下：
![GwqdLF.png](https://s1.ax1x.com/2020/04/04/GwqdLF.png)

**Comment by mtobeiyf** [comment]
修改 Listing 环境的字体不需要设置全局的字体。首先在 `.cls` 中引入包 `\usepackage[T1]{fontenc}`
在使用 Listing 环境前通过 `\lstset` 命令设置字体：

```latex
\lstset{basicstyle=\def\fvm@Scale{0.85}\fontfamily{fvm}\selectfont, frame=single, breaklines=true}

\begin{lstlisting}[language=Python,frame=single]
import numpy as np

a = np.zeros((2,2))
print(a)
\end{lstlisting}
```

注意 Scale 参数能够调整字体的大小，显示效果为：
![image](https://user-images.githubusercontent.com/5097752/78456251-910a2f80-7670-11ea-8586-88809e372313.png)

还可以通过 package 的方式使用 DejaVu Sans Mono 等其它等宽字体。

更多参考：
- https://tex.stackexchange.com/questions/174892/what-is-the-least-invasive-way-to-set-the-font-for-listings
- http://nepsweb.co.uk/docs/progfonts.pdf
