### ISSUE TITLE
LaTex 后添加新段落

### ISSUE THREAD

**Issue by hwongbaul** [mtobeiyf/whu-thesis#13]
在新生成的 demo pdf 文件和自行编译的 pdf 文件中，以 `LaTex` 开头的段落会在 LaTex 后另起一个段落。

> Updated Version
![image](https://user-images.githubusercontent.com/8535390/78999893-28deb080-7b7e-11ea-87ff-b705ee5b125a.png)

![image](https://user-images.githubusercontent.com/8535390/78999956-4b70c980-7b7e-11ea-8ff8-9a86e2162567.png)

> Old Version
![image](https://user-images.githubusercontent.com/8535390/78999941-427ff800-7b7e-11ea-81a7-00209a23a664.png)

![image](https://user-images.githubusercontent.com/8535390/78999979-588db880-7b7e-11ea-9113-7fda46ad98cc.png)

**Comment by T0nyX1ang** [comment]
初步判断是cls文件中引入的\RequirePackage{txfontsb}导致的这个问题，但是写文章应该也不会用\LaTeX 这个命令吧，所以应该没啥影响。

**Comment by tanukihee** [comment]
`txfontsb` 包也比较老了，而且会同时影响正文字体与数学字体，换一个吧，换 `newtxmath` 包吧，只改变数学字体。

**Comment by tanukihee** [comment]
> `txfontsb` 包也比较老了，而且会同时影响正文字体与数学字体，换一个吧，换 `newtxmath` 包吧，只改变数学字体。

不行，`newtxmath` 的数字风格不对，还是换 `txfonts` 吧（虽然这个更老）

**Comment by tanukihee** [comment]
![image](https://user-images.githubusercontent.com/34062491/79005276-10c05e80-7b89-11ea-87b6-55ffcbecf187.png)
`txfonts`
![image](https://user-images.githubusercontent.com/34062491/79005366-46fdde00-7b89-11ea-990f-4ec2073980bb.png)
`newtxmath`

**Comment by tanukihee** [comment]
![image](https://user-images.githubusercontent.com/34062491/79005866-6ba68580-7b8a-11ea-8367-b8d71539f761.png)
奇怪，`newtxfonts` 文档似乎一切正常，也许要和 `newtxtext` 一起使用吧
![image](https://user-images.githubusercontent.com/34062491/79006204-3e0e0c00-7b8b-11ea-8e61-7fddef00be4f.png)

但是此时正文字体又变成 cm 了😂

**Comment by mtobeiyf** [comment]
似乎 `newtxmath` 或者 `txfonts` 都不能简单的解决这个问题。
比较好的方式是确保正文的 `\LaTeX` 不在行首（在之前写点字）或者干脆换成 英文的 `LaTeX`
再用 `txfonts` 代替 `txfontsb` 来使封面页的 `\LaTeX` 不换行。 🤔
