### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by kleinzcy** [mtobeiyf/whu-thesis#16]
感谢你分享的模板。

环境：latex2019, vscode

你的模板能编译成功。修改主要内容之后，使用recipe: xelatex->bibtex->xelatex*2编译不成功，提示Reference `fig:model' on page 3 undefined.，即\ref和\label不匹配，并且所有reference都undefined。我确信，fig:model我定义过。并且所有reference都在bib文件中。

我尝试换recipe，先使用xelatex->bibtex->xelatex*2编译失败后，再xelatex*2就成功了，不明白为什么？

我添加以下宏包：
\usepackage{caption}
\usepackage{ulem}
\usepackage{textcomp}
\usepackage{tipa}
\usepackage{dsfont}
\usepackage{bm}
\usepackage{mathrsfs}
\usepackage{multirow}

并修改  \bibliography{ref/refs} 为  \bibliography{main}

**Comment by tanukihee** [comment]
需要提供 MWE（最小工作示例）

**Comment by mtobeiyf** [comment]
> 你的模板能编译成功。修改主要内容之后，使用recipe: xelatex->bibtex->xelatex*2编译不成功

这就是你修改的内容的问题了

How to debug:
我感觉是你编译过程中的某一步出现了问题（可能是 bibtex），导致最后的 xelatex 将编译中间生成的不完整的文件一起编译。你可以手动按顺序执行命令，看每一步的报错信息。
