### ISSUE TITLE
where to put `\usetikzlibrary` ?

### ISSUE THREAD

**Issue by uzabon** [mtobeiyf/whu-thesis#2]
To draw a flow chart or sequence chart , the source code provided by overleaf is always contained with some lines like `\usetikzlibrary{arrows}`. But no matter where I put the code , the editor cannot parse it correctly and usually ignores it.
Any idea ? or just recommend a jpg for simpilicity?

I am writing in overleaf on firefox.

**Comment by mtobeiyf** [comment]
I'm not sure what you mean by "the editor usually ignores it". But it's easy to use the tikz library to draw the flow chart. 
And you can put the `\usetikzlibrary{arrows}` anywhere before the `\begin{tikzpicture}` command.
For example
![image](https://user-images.githubusercontent.com/5097752/56256712-6ab85080-60fc-11e9-9a89-42a3b7c0f1a7.png)

If you do not like seeing these configuration commands in the document body, you could put the `\usetikzlibrary{...}` and `\tikzstyle` at the end of the `.cls` file.
