### ISSUE TITLE
`ctex` 宏集大更新

### ISSUE THREAD

**Issue by tanukihee** [mtobeiyf/whu-thesis#20]
从 2020.05.01 的 `v2.5` 开始，`xeCJKfntef` 包不会自动载入了，画下划线需要手动载入 `ulem` 包或者 `xeCJKfntef` 包了，不然封面的编译就过不了。

另外，似乎 #19 中，公式西文字体数字又变成 latin modern 了，但在我电脑中没有出现这种情况……

[参考这里](https://zhuanlan.zhihu.com/p/137711348)

**Comment by mtobeiyf** [comment]
可以帮忙提交一个 PR 解决一下 ctex 2.5 的兼容性问题。我最近可能没什么时间研究这个。

PR #19 里面的公式西文字体的设置没有变动，可能是他电脑环境的问题。
