### ISSUE TITLE
表格标题不是黑体

### ISSUE THREAD

**Issue by ChenglinYu** [mtobeiyf/whu-thesis#22]
表格标题不是黑体

**Comment by T0nyX1ang** [comment]
#17 已经对此进行了改正，请更新版本。

**Comment by mtobeiyf** [comment]
请参考最新 [关于认真做好2020届本科生 毕业论文（设计）答辩工作的通知](https://info.whu.edu.cn/info/1318/185710.htm) 附件中关于表格标题的陈述。
当前版本的表格标题参照了书写印制规范中的要求：
> 表标题和表序号居中置于表上方（黑体小4号，数字和字母为Time New Roman粗体小4号）

![](https://user-images.githubusercontent.com/5097752/82124716-e0af4100-976e-11ea-9da6-604b03653af9.png)

**Comment by ChenglinYu** [comment]
I complied the updated template with overleaf. But the result is as follows:

![image](https://user-images.githubusercontent.com/29471111/82132211-e14be400-980f-11ea-8cb7-b015f7b6cf24.png)

Clearly, the caption's font is not heiti.
