### ISSUE TITLE
目录红色方框引用

### ISSUE THREAD

**Issue by kleinzcy** [mtobeiyf/whu-thesis#24]
![image](https://user-images.githubusercontent.com/35723500/82172081-c9ea2500-98fb-11ea-9de2-a44134834c90.png)

作者，你好，请问怎么去掉这些红色方框引用？被老师要求修改。

**Comment by tanukihee** [comment]
最简单的方法是注释掉 `hyperref`，要保留超链接的话可以自己照着手册调

这些红方框是不会打印出来的……

**Comment by tanukihee** [comment]
![image](https://user-images.githubusercontent.com/34062491/82172778-c22b8000-98fd-11ea-99bb-729004b72a4b.png)
`hidelinks` 选项亦可

**Comment by kleinzcy** [comment]
@tanukihee 多谢，已解决，使用你说的hidelinks。目前都是线上答辩，这些红框就被要求修改了。

**Comment by mtobeiyf** [comment]
在 `\hypersetup` 后添加 `hidelinks` 即可

```diff
- \hypersetup{citecolor=magenta,linkcolor=black,urlcolor=blue} % 设置引用链接颜色 
+ \hypersetup{citecolor=magenta,linkcolor=black,urlcolor=blue,hidelinks} % 设置引用链接颜色
```
