### ISSUE TITLE
[Feature Request] Apply CI into this project

### ISSUE THREAD

**Issue by T0nyX1ang** [mtobeiyf/whu-thesis#25]
由于每个人编译示例文档的结果都不太一样，希望引入持续集成测试来给出一个**相对官方**的预览版本。目前我找到的CI只支持linux+最新的texlive，直接用github actions实现，但是似乎linux上面没有times new roman这个字体来着，所以编译阶段都会报错。我写好的CI文件可以见[这里](https://github.com/T0nyX1ang/whu-thesis/actions/runs/111621948)，希望有大佬能搞定linux上面的times new roman的字体安装，方便预览工作。

CI编译错误信息：
```
kpathsea:make_tex: Invalid filename `Times New Roman', contains ' '
kpathsea:make_tex: Invalid filename `Times New Roman', contains ' '
kpathsea:make_tex: Invalid filename `Times New Roman', contains ' '
kpathsea:make_tex: Invalid filename `Times New Roman/BI', contains ' '
kpathsea:make_tex: Invalid filename `Times New Roman', contains ' '
kpathsea:make_tex: Invalid filename `Times New Roman/B', contains ' '
kpathsea:make_tex: Invalid filename `Times New Roman', contains ' '
kpathsea:make_tex: Invalid filename `Times New Roman/I', contains ' '
kpathsea:make_tex: Invalid filename `Times New Roman', contains ' '
kpathsea:make_tex: Invalid filename `Times New Roman', contains ' '
kpathsea:make_tex: Invalid filename `Times New Roman', contains ' '
(/opt/texlive/texdir/texmf-dist/tex/latex/txfonts/txfonts.sty)

./WHUBachelor.cls:133: Package fontspec Error: The font "Times New Roman" canno
t be found.
```

**Comment by mtobeiyf** [comment]
我之前有考虑过用 CI 自动编译预览，最近没有时间弄。
在 [latex-action](https://github.com/xu-cheng/latex-action) 的 `pre_compile` 里面可以添加 bash 命令，那么可以安装 Time New Roman 的 [package](https://pkgs.alpinelinux.org/package/edge/community/x86/msttcorefonts-installer) 
`apk --no-cache add msttcorefonts-installer fontconfig && update-ms-fonts && fc-cache -f `
SimSun 和 SimHei 的字体还需要另外再配置。

GitHub Action 也有 [Window 镜像](https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners#supported-runners-and-hardware-resources)，可以安装 MiKTeX 之类的工具包来构建，问题是英文版的系统应该是没有 SimSun 和 SimHei 的。

**Comment by T0nyX1ang** [comment]
TNR的问题解决了，我等会会放一个PR出来构建linux上面的CI测试。（然后似乎linux上面有相关的宋体和黑体）

**Comment by mtobeiyf** [comment]
宋体和黑体用的是Fandol。我在 Windows 看的效果是和宋体一样。
还有 GitHub 能直接上传 pdf 么

**Comment by T0nyX1ang** [comment]
把生成的pdf变成一个commit上传恐怕不太好，但是Github Action中可以生成artifacts，里面下下来是一个zip，包含了pdf，我在#26的PR已经实现了这一点。

**Comment by mtobeiyf** [comment]
不 我指的是 GitHub Action 的 artifacts 直接上传生成的 pdf 文件而不是打包成 zip。这样比较方便预览。
https://github.com/actions/upload-artifact#upload-an-individual-file

**Comment by T0nyX1ang** [comment]
看那个描述似乎可以直接传文件了，但我目前在artifacts里下载的还是zip，具体操作感觉还要试一下水。

**Comment by mtobeiyf** [comment]
确实是直接上传了单个 pdf 文件，下载变成 zip 是 UI limitation。

> Right now in order for everything to be downloaded at once, a zip gets dynamically created when you click to download the artifact. This zip is a UI limitation and it is independent of how the artifact gets upload.

https://github.com/actions/upload-artifact/issues/3#issuecomment-620722206
