### ISSUE TITLE
目录样式中三级目录缩进有误

### ISSUE THREAD

**Issue by 0oshowero0** [mtobeiyf/whu-thesis#3]
二级目录(如1.1)与三级目录(如1.1.1)缩进相同，与格式要求不符

格式要求：
![image](https://user-images.githubusercontent.com/21094960/56470462-eefe3100-6478-11e9-9010-1cc1d8728203.png)

(另外要求目录标题是第x章而不是x，貌似不是很好改。。)

**Comment by mtobeiyf** [comment]
你的模板是哪个版本的 :joy:
这个是示里面的
![image](https://user-images.githubusercontent.com/5097752/56471948-0d6d2800-648b-11e9-90da-46cca16f92b1.png)

关于标题和目录的格式，毕业论文规范里面有：
![image](https://user-images.githubusercontent.com/5097752/56471979-6c32a180-648b-11e9-9e7e-5c8c5c900143.png)

![image](https://user-images.githubusercontent.com/5097752/56471983-7f457180-648b-11e9-9851-cc8a48cffbc1.png)

[武汉大学本科生毕业论文（设计）范例](http://210.42.121.231/bysj/ShowNews.aspx?newsno=l6qXTmVXTTHAGYYEUKAUeg....)

[武汉大学本科生毕业论文（设计）书写印制规范](http://210.42.121.231/bysj/ShowNews.aspx?newsno=TAP/rsNayLeZfiIRC/fCGw....)

**Comment by 0oshowero0** [comment]
这个是以前院里给的范例😂 那就先这样吧
