### ISSUE TITLE
texlive2019 error

### ISSUE THREAD

**Issue by GreenTeaHua** [mtobeiyf/whu-thesis#31]
\tl_if_eq:NnTF  ----->  \tl_if_eq:nnTF
texlive2019

**Comment by tanukihee** [comment]
请提供详细的错误信息，如果有必要请上传 .log 文件

**Comment by tanukihee** [comment]
`\tl_if_eq:NnTF` 是 2020-07-14 引入 expl3 的，请用 texlive 2020 编译。

**Comment by GreenTeaHua** [comment]
谢谢，实验室统一2019的环境/(ㄒoㄒ)/~~

**Comment by tanukihee** [comment]
可以先用 overleaf，我看类似反馈多不多再决定改不改（还有 4 个月就出 2021 啦）
