### ISSUE TITLE
开题报告的tex文件编译后右边界出现了tabulartabular这种英文文字

### ISSUE THREAD

**Issue by frankdarkluo** [mtobeiyf/whu-thesis#34]

**Comment by Fassial** [comment]
I solved this problem by updating all packages of latex, more details at #35 .
Hope this helps.

**Comment by frankdarkluo** [comment]
> I solved this problem by updating all packages of latex, more details in #35 .
> Hope this helps.

Thanks a lot, but I intend to use it in overleaf, it seems that there is no way to update packages in overleaf, or do you know how to solve it based on using overleaf?

**Comment by tanukihee** [comment]
可以复现，简单解决办法：使用 lua 编译，或者在cls的第314行之前引入 etoolbox

Fixed in dev.

**Comment by tanukihee** [comment]
> I solved this problem by updating all packages of latex, more details in #35 .
> Hope this helps.

`\AtBeginEnvironment` 这个钩子在 2020/10 的 LaTeX 中扶正了，以前是 etoolbox 的钩子。

**Comment by tanukihee** [comment]
> 可以复现，简单解决办法：使用 lua 编译

用 lua 编译能解决问题的原因则是因为 luatexja 会自动调用 etoolbox
