### ISSUE TITLE
Cannot compile with latex2020.

### ISSUE THREAD

**Issue by Fassial** [mtobeiyf/whu-thesis#35]
I am not very familiar with latex. When I use overleaf to compile this project(with latex2020), there is no error in whuthesis.cls.
But when I compile this project locally with latex2020(from tuna, 2020.4), it generates such error:
```
! Undefined control sequence.
l.114 \tl_if_eq:NnTF
                     \l__whu_class_tl { opening }
```
I really need your help, thx a lot!

**Comment by Fassial** [comment]
And when I use overleaf to compile this project with latex(<2019), it always generates the same error.

**Comment by Fassial** [comment]
Sorry for not reading the [guide-doc](https://github.com/mtobeiyf/whu-thesis/blob/master/whuthesis-doc.pdf) before asking the question.
I have solved this problem by updating all the packages of latex:
```
tlmgr update --self --all
```
If you have font problems like this:
```
! Font TU/TimesNewRoman(0)/m/n/10.53937="Times New Roman" at 10.53937pt not loa
dable: Metric (TFM) file or installed font not found.
<to be read again> 
                   relax 
l.30 \begin{document}
```
you can solve this by typing the following command:
```
sudo apt install ttf-mscorefonts-installer
sudo fc-cache
```

**Comment by tanukihee** [comment]
字体配置也在 dev 中修复了

**Comment by tanukihee** [comment]
`\tl_if_eq:NnTF` 是 2020-07-14 引入 expl3 的，早期 texlive 2020 确实不行，如果有必要的话（看类似反馈多不多）可能会照顾早版本用户改一改

**Comment by mtobeiyf** [comment]
@tanukihee 如果这个2020新feature不是必须的话建议去掉或者改成兼容旧版本以及Overleaf环境。尽量开箱即用。

**Comment by tanukihee** [comment]
> @tanukihee 如果这个 2020 新 feature 不是必须的话建议去掉或者改成兼容旧版本以及 Overleaf 环境。尽量开箱即用。

overleaf 已经更新到 2020，支持这个了

**Comment by wzm2256** [comment]
首先感谢提供这个模板。

我只能说太难了，升级texlive的命令又带来其他麻烦。
我执行升级命令 `tlmgr update --self --all`
输出
```
Cannot determine type of tlpdb from H:!
tlmgr.pl: Cannot load TeX Live database from H:
```
我当时直接用虚拟光驱装的texlive 17，这个H是我虚拟光驱的地址。

我又试了其他用GUI界面升级texlive 的方式，
``tlmgr --gui`` 界面卡半天，不知道到底卡死了还是在升级。

这个feature能去掉吗？用latex本身就是图方便，为啥要用不向后兼容的新特性呢？
我之前用texlive编译很多其他文档，我升级以后这些文档没人保证编译结果一样啊。。

**Comment by tanukihee** [comment]
> 首先感谢提供这个模板。
> 
> 我只能说太难了，升级texlive的命令又带来其他麻烦。 我执行升级命令 `tlmgr update --self --all` 输出
> 
> ```
> Cannot determine type of tlpdb from H:!
> tlmgr.pl: Cannot load TeX Live database from H:
> ```
> 
> 我当时直接用虚拟光驱装的texlive 17，这个H是我虚拟光驱的地址。
> 
> 我又试了其他用GUI界面升级texlive 的方式， `tlmgr --gui` 界面卡半天，不知道到底卡死了还是在升级。
> 
> 这个feature能去掉吗？用latex本身就是图方便，为啥要用不向后兼容的新特性呢？ 我之前用texlive编译很多其他文档，我升级以后这些文档没人保证编译结果一样啊。。

当时想的是 overleaf 支持就没问题，现在退回去也不太可能了，你也用 overleaf 编译呗

**Comment by sikouhjw** [comment]
> 我当时直接用虚拟光驱装的texlive 17

1. texlive 不能直接跨版本升级
2. 你可以去下载最新的 tlmgr，再进行升级

**Comment by wzm2256** [comment]
> 

用GUI升级会提示要升级texlive manage，按照它的提示来应该是可以升级到21。但是实际上特别卡，而且看不到进度。。
我已经下载好了texlive21了，打算重装。

**Comment by wzm2256** [comment]
> > 首先感谢提供这个模板。
> > 我只能说太难了，升级texlive的命令又带来其他麻烦。 我执行升级命令 `tlmgr update --self --all` 输出
> > ```
> > Cannot determine type of tlpdb from H:!
> > tlmgr.pl: Cannot load TeX Live database from H:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我当时直接用虚拟光驱装的texlive 17，这个H是我虚拟光驱的地址。
> > 我又试了其他用GUI界面升级texlive 的方式， `tlmgr --gui` 界面卡半天，不知道到底卡死了还是在升级。
> > 这个feature能去掉吗？用latex本身就是图方便，为啥要用不向后兼容的新特性呢？ 我之前用texlive编译很多其他文档，我升级以后这些文档没人保证编译结果一样啊。。
> 
> 当时想的是 overleaf 支持就没问题，现在退回去也不太可能了，你也用 overleaf 编译呗

overleaf是在用，但是本地也要有个环境才行。。我打算重装21了

**Comment by wzm2256** [comment]
> > 我当时直接用虚拟光驱装的texlive 17
> 
> 1. texlive 不能直接跨版本升级
> 2. 你可以去下载最新的 tlmgr，再进行升级

用GUI升级会提示要升级texlive manage，按照它的提示来应该是可以升级到21。但是实际上特别卡，而且看不到进度。。
我已经下载好了texlive21了，打算重装。
