### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by R-JunmingChen** [mtobeiyf/whu-thesis#4]
1. 表格以及图序号

表格以及图序号在示例中使用的是times new roman，小四，加粗，
图与表的标题是对的

2. 参考文献格式

看设置导入的是gbt7714-2005，但是会议论文似乎和示例是不一样的。后缀似乎不对。
这是示例里的
![image](https://user-images.githubusercontent.com/18380073/56569300-47554000-65eb-11e9-9b8f-307e76fc58ec.png)

这是我在latex里生成的
![image](https://user-images.githubusercontent.com/18380073/56569402-7b306580-65eb-11e9-93f1-f8d088408ed1.png)

[A][C]这些对论文和会议的后缀不对？

老哥我对latex不是很熟，我也看看怎么搞

**Comment by mtobeiyf** [comment]
1. 图和表的标题应该是设置成了小四
具体看这里：https://github.com/mtobeiyf/whu-thesis/blob/master/WHUBachelor.cls#L100

2. 参考文献格式用了这里的 https://github.com/Haixing-Hu/GBT7714-2005-BibTeX-Style
理论上是没有问题的。国内的定义和国外是不一样的，会议论文接收后是`inproceedings`，属于“会议录中的析出文献（会议论文）” 
如果实在强求格式，那只能手动输入了。
bibtex为：
```
@inproceedings{毛峡2003和谐图案的自动生成研究,
author={毛峡 and 孙云},
title={和谐图案的自动生成研究},
booktitle={第一届中国情感计算及智能交互学术会议论文集},
year={2003},
pages={277-281},
address={北京},
month={9},
organization={[中国自动化学会, 中国中文信息学会, 中国计算机学会, 中国图像图形学会]},
publisher={中国自动化学会},
}
```
效果：
![image](https://user-images.githubusercontent.com/5097752/56573326-6b1c8400-65f3-11e9-9d94-a046fe3f1382.png)

gbt7714-2005中的参考
![image](https://user-images.githubusercontent.com/5097752/56572634-0876b880-65f2-11e9-84ac-5ef3e22db9f4.png)

**Comment by R-JunmingChen** [comment]
1. 图序号
表格以及图标题的汉字格式都是对的

图序号没有加粗- -，就这一个问题

2. 参考文献
是的，gbt7714-2005似乎和我们学校给的示例不太一致。
打算手动了- -

小哥你是做质量评价这块的吗

**Comment by mtobeiyf** [comment]
1. 我这里示例里面也没有加粗 
[武汉大学本科生毕业论文（设计）范例](http://210.42.121.231/bysj/ShowNews.aspx?newsno=l6qXTmVXTTHAGYYEUKAUeg....)
2. 按国标示例就对了

是的，以前搞这个。

**Comment by R-JunmingChen** [comment]
嗯嗯，问题解决了
1.最新版的没有加粗
2.就按标准的示例了

**Comment by mtobeiyf** [comment]
最新版的已经修改成按照武汉大学毕业论文的格式了 🍺 
![image](https://user-images.githubusercontent.com/5097752/56967519-efdb4500-6b93-11e9-91d2-597c4474bf9c.png)

**Comment by HElenZWHU** [comment]
请问https://github.com/whutug/whu-thesis/issues/250这个问题该如何解决呢
