### ISSUE TITLE
代码运行错误

### ISSUE THREAD

**Issue by WayneCaesar** [mtobeiyf/whu-thesis#5]
![1](https://user-images.githubusercontent.com/45967675/56725326-3ccbaf80-677f-11e9-99b7-7f8d3bd93441.png)
能帮忙解决一下吗？谢谢

**Comment by WayneCaesar** [comment]
![2](https://user-images.githubusercontent.com/45967675/56725446-713f6b80-677f-11e9-8e61-16458b67b355.png)
具体是这一行

**Comment by mtobeiyf** [comment]
你有用到文档里的代码高亮么？

那一行有说明 https://github.com/mtobeiyf/whu-thesis/blob/master/pages/chapter4.tex#L25
你需要系统安装python，并且随后安装pygments库：`pip install Pygments`

当然，用Overleaf就能直接使用。

如果不需要这个，也可以注释掉这行 https://github.com/mtobeiyf/whu-thesis/blob/master/WHUBachelor.cls#L138

**Comment by WayneCaesar** [comment]
嗯 安装Pygments库就好了 感谢指导 :+1:
