### ISSUE TITLE
False math fonts

### ISSUE THREAD

**Issue by tanukihee** [mtobeiyf/whu-thesis#8]
示例中的数学字体并不是 Times，而是默认的 Latin Modern。
![image](https://user-images.githubusercontent.com/34062491/78265549-2b665800-7537-11ea-8177-31400c6db11d.png)

可以使用 `unicode-math` 包改变数学字体，使用 [TeX Gyre](http://www.gust.org.pl/projects/e-foundry/tex-gyre) 系列的 TeX Gyre Termes、[XITS](https://github.com/alif-type/xits) 或 [STIX](http://stixfonts.org/) 等 Times 风格数学字体（需要自行安装）：
```TeX
\usepackage{unicode-math}
\setmathfont{TeX Gyre Termes Math} % 数学字体名
```
![image](https://user-images.githubusercontent.com/34062491/78265935-b0ea0800-7537-11ea-90b6-28ef28fa17e1.png)

或者在 `amsmath` 包后面使用  `txfonts` 或 `txfontsb` 包，并将
```TeX
\setmainfont{Times New Roman}
\setsansfont{Times New Roman}
\setmonofont{Times New Roman}
```
移至 
```TeX
\RequirePackage{amsmath, amssymb}
```
后即可
![image](https://user-images.githubusercontent.com/34062491/78266488-6f0d9180-7538-11ea-84ff-e45c0869ad0c.png)

两者几乎无差别。

**Comment by mtobeiyf** [comment]
Merged #9
